#
# This file is the source of truth for the versions of the libraries used in
# the project. Any library that is managed by a Bill of Materials such as
# Spring Boot, Spring Cloud, Test Containers ... etc. inherts the version
# specified in the BOM.
#

[versions]

# BOM versions
springAi = "2.0.0-M2"
springBoot = "4.0.2"
springCloud = "2025.1.1"

# testing utilities
equalsVerifier = "4.3.1"
threeTenExtra = "1.8.0"
mcpJavaSdk = "0.17.2"
awaitility = "4.3.0"
thymeleafSpringSecurityExtras = "3.1.3.RELEASE"

[libraries]

# Spring Boot
spring-boot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starter-test-testContainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springBoot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "springBoot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBoot" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "springBoot" }
spring-boot-starter-oauth2-authorization-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server", version.ref = "springBoot" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server", version.ref = "springBoot" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway", version.ref = "springBoot" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient", version.ref = "springBoot" }

spring-boot-jackson2 = { module = "org.springframework.boot:spring-boot-jackson2", version.ref = "springBoot" }
spring-boot-restclient = { module = "org.springframework.boot:spring-boot-restclient", version.ref = "springBoot" }
spring-boot-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient", version.ref = "springBoot" }

# Spring AI
spring-ai-bom = { module = "org.springframework.ai:spring-ai-bom", version.ref = "springAi" }
spring-ai-starter-model-openai = { module = "org.springframework.ai:spring-ai-starter-model-openai", version.ref = "springAi" }
spring-ai-starter-mcp-client = { module = "org.springframework.ai:spring-ai-starter-mcp-client", version.ref = "springAi" }
spring-ai-starter-mcp-server-webmvc = { module = "org.springframework.ai:spring-ai-starter-mcp-server-webmvc", version.ref = "springAi" }

# Spring Cloud
spring-cloud = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
spring-cloud-gateway-mvc = { module="org.springframework.cloud:spring-cloud-starter-gateway-server-webmvc" }

# Libraries

# test helpers
equalsVerifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsVerifier" }
threeTenExtra = { module = "org.threeten:threeten-extra", version.ref = "threeTenExtra" }
testContainers-postgres = { module = "org.testcontainers:testcontainers-postgresql" }
testContainers-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
thymeleaf-extras-springsecurity6 = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6", version.ref = "thymeleafSpringSecurityExtras" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }